# .streamlit/secrets.toml

# Coloque sua NOVA chave do Gemini aqui
GOOGLE_API_KEY = "AIzaSyCv9L-emeQXG8ziG5RIpLSvV88pxLbZh44"

# Suas credenciais do Firebase (para o frontend)
[firebase_config]
apiKey = "AIzaSyAuRxH97q5d7gSRf723hrUjyV-tjmg3m-M"
authDomain = "max-marketing-total.firebaseapp.com"
projectId = "max-marketing-total"
storageBucket = "max-marketing-total.firebasestorage.app"
messagingSenderId = "442279100976"
appId = "1:442279100976:web:f53a9eacea9a14324f63f5"
measurementId = "G-206VHFW8MG"

# Sua conta de serviço (para o backend)
# Copie os valores do NOVO arquivo JSON que você baixou
[gcp_service_account]
type = "service_account"
project_id = "max-marketing-total"
private_key_id = "6218a8ef0fff60ee826fc65e7c1d4b4656835d61"
private_key = ""-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSiTTxgib2hGez\nYCcZGFhVrss4ksvhJENOumqWbCxX2oeJgI8KFSC2kXnBGheJ1ccW35ZcNOrWRDSh\nmq/1tN49VZFKYwinqsyFOdYGnkqkIkbI2toWNI47Ab2cp+8285dxnr9rxzck5tkE\nHxlVUEeONKYm0xv6qOmLolArKYZD3SLZchn9+aloV5OhDVFhrlczQk3zJ1WE/k8m\nmWxUX49wldMgO6jSFJR1S8drIXZv2jFI6CXzi6HLtn6pebsMtJ/KcWTSxnCXhoiF\nGm5GoTcKin/zJ6XpJ1fQmYuTd1Kn/q89yLGFDONZ3HBydx2M4VameRiI7sKPR5pT\n2zchAsB1AgMBAAECggEAK0Qs6DQ0Oex9TAbTdILuLhpmsaUSYr8YyombSB/Xdfc1\ntsFJOsJjPtS0XPJNyepflt7coAwV3L8VxTONyeAmEHkP5aVZHFx/d8TMb3bUdiMS\nwGJyK0VIS57nc/ZX2ONSr38eaP3Qx+oLYL6n9bs27YOZHXSO2dN+5bY+sofXt3iE\no5Th7rGOfc9INiQ+ZfHVn+ZTf7wjtRpRKLquLWg8S4jm7ee2cp9NARdT7qqtZBpS\nc94EaFGqX7Ju/pqxaHC70oJWGR5H5fDT4pQFEKDyzmfMSxa1iaMT7auZxKs7Gwzp\nmEUFI6I7Qw9H42UyAqofuCAIrfdRCwwDhXLZFmyOHwKBgQDOTjpanVFZqUOSMFdd\njwY9JGKa2AI2vbQ9zGBqHl1JJ0u/qriI/WizWgMvrXocpqiXeKkRiwqhTiTaQxrH\n1KC3PhXmyJQQwdqN6VpKI/IZX4br62+sMS2zbK4pztBR8m2bvO5wRBTl5lgEYdx1\nto3qFd+0eX3cSRVMCMD9BGEs2wKBgQC11U2s7YbYPrG1jKwTc9LVJFAnIQzZ6j+R\nDQRFGv7At2I9i4fyz/+AjTFjPTZecGTFtqdx1NjWZvmqDGZ6Qj4scIUoW9TyTAcX\n/h7o5CdtUacuC164VwAcTpl6YoxLjVrhCwjYIQwdGxwUqTTyi/rtDenc2MvLJ79s\n6ECbDhOg7wKBgQCRemx/1Yu2FDwH7HrPCLo3h17ZHhWBkIh3Q5WBf2P83+70e2ih\ngUDBqGmyxzvi1ErydS2Tp16ZnMcz+jn6TCAA15EOKsbugiSiCbmXqn1gExLLbjxT\nSmKVsb+mz6XrA27zcWkaVYf/Dk1m2bNidpbgSQh09W8hVY/lDA863EnCHQKBgBcg\n2pB0ZgJ7dv8wtXKD+P1DcS6I9amCMjOxBCoGFQFOUiCh7tjjvAwN6YpF7vR0N10u\nrn28JRigYIFQsng6lM3yQf2wMJXhNcXHfQcCfkFZcXpZ1+J6rnjrRnparp2tjTGy\nxZ04FuJc4GWAYEu5omEks+pzaPieRasEn7MZR0XhAoGAXD7rz17FBN5tAk3MRzvd\nD7RaD/mNm8os6+Un6PtCzMGN5hUgKLPSHNyVm2it8m5LN4/ztjzfQSchIPpERMJK\nsAqpjtZoIp+w3ewCdtAeMX+3RxcT4bXW1WsVT07e5cfqUZwSIEgf0j4CHXy71kX8\nepP/2OZxhU1DaH8GBPTQzRI=\n-----END PRIVATE KEY-----\n","
client_email = "firebase-adminsdk-fbsvc@max-marketing-total.iam.gserviceaccount.com""
client_id = "102150144086379728868"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40max-marketing-total.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
